[setup]
boxlength = 148.148148  # 100 Mpc/h
zstart = 99.0           # CAMB z_start
levelmin = 7            # 128 resolution
levelmin_TF = 7
levelmax = 7
region = box
align_top = yes
blocking_factor = 32
baryons = yes
use_2LPT = no          # Zel'dovich linear approx for z=99
use_LLA = no
periodic_TF = yes      # periodic boundary condition for the Fourier transform

[cosmology]
Omega_m			= 0.316049
Omega_L			= 0.683951
w_0			    = -1.0
w_a			    = 0.0
Omega_b			= 0.048285
H0			    = 67.5           # Hubble constant (now)  km/s/Mpc
sigma_8			= 0.811
n_s			    = 0.965
gamma           = 5.0 / 3.0
transfer		= camb_file
transfer_file   = ./CAMB_lcdm_matter_power_z99.0.txt


[random]
seed[7]			= 12345
seed[8]			= 23456
seed[9]			= 34567
seed[10]		= 45678
seed[11]		= 56789
seed[12]		= 67890


[output]
##generic MUSIC data format (used for testing)
##requires HDF5 installation and HDF5 enabled in Makefile
#format			= generic
#filename		= debug.hdf5


# proseguire ad matchare con camb e quokka e a fare un output leggibile da quokka